num_agents: 3
iterations: 2
use_summary: true
use_parallel: true  # CPU最適化のため並列処理を有効化
use_memory: true
performance_monitoring: true
memory_tracking: true
debug: false

# ログ設定
log_level: INFO
log_file: logs/murmurnet.log

# モデル設定
model_type: llama
model_path: "C:\\Users\\admin\\Desktop\\課題研究\\models\\gemma-3-1b-it-q4_0.gguf"
chat_template: "C:\\Users\\admin\\Desktop\\課題研究\\models\\gemma3_template.txt"
n_ctx: 4096  # CPU最適化のため8192から4096に調整
n_threads: 8  # CPU最大活用のため8スレッドに増加
temperature: 0.7
max_tokens: 200  # CPU負荷軽減のため256から200に調整
model_cache_dir: "cache/models"  # モデルキャッシュディレクトリ

# CPU最適化設定
cpu_optimization:
  max_parallel_agents: 4  # 最大並列エージェント数
  thread_pool_size: 8     # スレッドプールサイズ
  process_pool_size: 4    # プロセスプールサイズ
  enable_vectorization: true  # ベクトル化を有効化
  enable_caching: true    # キャッシュを有効化
  batch_size: 512         # バッチサイズ最適化

# エージェント設定
role_type: default

# RAG設定（CPU最適化版）
rag_enabled: true
rag_mode: zim
zim_path: "C:\\Users\\admin\\Desktop\\課題研究\\KNOWAGE_DATABASE\\wikipedia_en_top_nopic_2025-03.zim"
rag_score_threshold: 0.5
rag_top_k: 3
embedding_model: "all-MiniLM-L6-v2"
embedding_cache_size: 1500  # CPU最適化: キャッシュサイズ増加
max_workers: 4  # 並列処理ワーカー数
batch_size: 32  # バッチ処理サイズ
enable_vectorization: true  # ベクトル化有効

# Blackboard設定（CPU最適化版）
blackboard_cache_size: 800  # LRUキャッシュサイズ
blackboard_history_size: 500  # 履歴サイズ制限
enable_async_buffer: true  # 非同期バッファ有効
buffer_size: 30  # バッファサイズ
flush_interval: 2.0  # フラッシュ間隔（秒）
history_retention_hours: 12  # 履歴保持時間
persistent_keys: 
  - conversation_context
  - agent_state
  - performance_metrics

# ベクトル化・並列処理設定
enable_vectorization: true
enable_parallel_processing: true
enable_async_buffer: true

# 要約設定
summary_max_length: 150  # CPU負荷軽減のため200から150に調整

# 会話記憶設定
conversation_memory_limit: 10
